theme: minima
title: Ajay Sadhu
author: ajaysadhu
email: your-email@domain.com
description: Work in Progress

# social links
twitter_username: ajsadhu
github_username:  ajaysadhu

show_excerpts: true # set to false to remove excerpts on the homepage
